version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9093:9093"
    command:
      - bash
      - -c
      - |
        /etc/confluent/docker/run &\n
        sleep 10 &&\n
        kafka-topics --create --topic chat_requests_generic --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 &&\n
        kafka-topics --create --topic chat_responses_generic --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 &&\n
        kafka-topics --create --topic chat_requests --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 &&\n
        kafka-topics --create --topic chat_requests --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 &&\n
        wait

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8080:8080"

  llm-worker-generic:
    build:
      context: .
      dockerfile: app/agent/Dockerfile
    container_name: worker-generic
    depends_on:
      - kafka-ui
    environment:
      OPENAI_TOKEN: "${OPENAI_TOKEN}"
      OPENAI_MODEL_NAME: "${OPENAI_MODEL_NAME}"
      OPENAI_HOST: "${OPENAI_HOST}"
      KAFKA_REQUEST_TOPIC: "chat_requests_generic"
      KAFKA_RESPONSE_TOPIC: "chat_responses_generic"
      BOOTSTRAP_SERVERS: kafka:9092
